CREATE DATABASE NetPublisherDB

GO
USE NetPublisherDB
GO

CREATE TABLE CARGA_ARCHIVO (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_ARCHIVO VARCHAR(200) NOT NULL,
    CORRE_USUARIO VARCHAR(150) NOT NULL,
    ARCHIVO_ID VARCHAR(100) NULL,
    [ESTADO_PROCESO] VARCHAR(50) NOT NULL,
    [USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_ACTUALIZACION] [varchar](50) NULL,
	[FECHA_ACTUALIZACION] [date] NULL,
	[ACTIVO] [bit] NOT NULL
);

GO

CREATE TABLE DATA_PROCESADA
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CARGA_ID INT NOT NULL,
    PERIODO VARCHAR(20) NOT NULL,
    CODIGO_PRODUCTO VARCHAR(50) NULL,
    CONSTRAINT FK_DataProcesada_CargaArchivo FOREIGN KEY (CARGA_ID)
        REFERENCES CARGA_ARCHIVO(Id)
);

GO

CREATE TYPE ProcessedDataType AS TABLE
(
    CargaId INT,
    Periodo VARCHAR(20),
    CodigoProducto VARCHAR(50)
);

GO

CREATE PROCEDURE InsertProcessedData
    @Data ProcessedDataType READONLY
AS
BEGIN
    INSERT INTO DATA_PROCESADA (CARGA_ID, PERIODO, CODIGO_PRODUCTO)
    SELECT CargaId, Periodo, CodigoProducto
    FROM @Data;
END