CREATE DATABASE NetAuthCompanyBD;

GO

USE NetAuthCompanyBD;


GO

CREATE TABLE [dbo].[ACCOUNT_ROL](
	[ACCOUNT_ROL_ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](80) NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_ACTUALIZACION] [varchar](50) NULL,
	[FECHA_ACTUALIZACION] [date] NULL,
	[ESTADO] [bit] NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[ACCOUNT_ROL] ADD PRIMARY KEY CLUSTERED 
(
	[ACCOUNT_ROL_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE TABLE [dbo].[ACCOUNT_USER](
	[ACCOUNT_USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMAIL] [varchar](80) NULL,
	[PASSWORD] [varbinary](max) NOT NULL,
	[SALT] [varbinary](max) NOT NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_ACTUALIZACION] [varchar](50) NULL,
	[FECHA_ACTUALIZACION] [date] NULL,
	[ESTADO] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[ACCOUNT_USER] ADD PRIMARY KEY CLUSTERED 
(
	[ACCOUNT_USER_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]



CREATE TABLE [dbo].[ACCOUNT_USER_ROL](
	[ACCOUNT_USER_ROL_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACCOUNT_USER_ID] [int] NOT NULL,
	[ACCOUNT_ROL_ID] [int] NOT NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_ACTUALIZACION] [varchar](50) NULL,
	[FECHA_ACTUALIZACION] [date] NULL,
	[ESTADO] [bit] NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[ACCOUNT_USER_ROL] ADD PRIMARY KEY CLUSTERED 
(
	[ACCOUNT_USER_ROL_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

ALTER TABLE [dbo].[ACCOUNT_USER_ROL]  WITH CHECK ADD FOREIGN KEY([ACCOUNT_ROL_ID])
REFERENCES [dbo].[ACCOUNT_ROL] ([ACCOUNT_ROL_ID])
ON DELETE CASCADE

ALTER TABLE [dbo].[ACCOUNT_USER_ROL]  WITH CHECK ADD FOREIGN KEY([ACCOUNT_USER_ID])
REFERENCES [dbo].[ACCOUNT_USER] ([ACCOUNT_USER_ID])
ON DELETE CASCADE



GO

CREATE PROCEDURE ValidateUserSP
(
    @pEmail VARCHAR(30)
)
AS 
BEGIN
    SELECT 
        A.[ACCOUNT_USER_ID],
        A.EMAIL AS [Email],
        A.PASSWORD,
        A.SALT AS [Salt],
        A.[USUARIO_CREACION],
        A.[FECHA_CREACION],
        A.[USUARIO_ACTUALIZACION],
        A.[FECHA_ACTUALIZACION],
        A.ESTADO
    FROM [dbo].[ACCOUNT_USER] A
    WHERE A.EMAIL = @pEmail;
END
GO

CREATE PROCEDURE ADD_ROL (@pDescription VARCHAR(50))
AS
BEGIN
    INSERT INTO [dbo].[ACCOUNT_ROL](DESCRIPTION, ESTADO) VALUES (@pDescription, 1);
END
GO

CREATE PROCEDURE RolList_SP
AS
BEGIN
    SELECT ACCOUNT_ROL_ID AS [RolId], [DESCRIPTION]
    FROM [dbo].[ACCOUNT_ROL];
END
GO

-- Insertar rol Admin
INSERT INTO dbo.ACCOUNT_ROL (DESCRIPTION, USUARIO_CREACION, FECHA_CREACION, ESTADO)
VALUES ('Admin', 'SYSTEM', GETDATE(), 1);

DECLARE @RolId INT = SCOPE_IDENTITY();

-- Insertar usuario Admin
INSERT INTO dbo.ACCOUNT_USER (EMAIL, PASSWORD, SALT, USUARIO_CREACION, FECHA_CREACION, ESTADO)
VALUES (
    'admin@empresa.com',
    CAST(N'' AS XML).value('xs:base64Binary("5GZD548kMMUM1lnP67WumHF96SYDEwMZRBLi+Oo55t4=")', 'VARBINARY(MAX)'),
    CAST(N'' AS XML).value('xs:base64Binary("aiVy89B8JEQo5PgriZ9/Cg==")', 'VARBINARY(MAX)'),
    'SYSTEM',
    GETDATE(),
    1
);

DECLARE @UserId INT = SCOPE_IDENTITY();

-- Asignar rol Admin al usuario
INSERT INTO dbo.ACCOUNT_USER_ROL (ACCOUNT_USER_ID, ACCOUNT_ROL_ID, USUARIO_CREACION, FECHA_CREACION, ESTADO)
VALUES (@UserId, @RolId, 'SYSTEM', GETDATE(), 1);

/*
SELECT * FROM ACCOUNT_ROL
SELECT * FROM ACCOUNT_USER
SELECT * FROM ACCOUNT_USER_ROL
*/